=== teleporthq/teleport-code-generators/packages/teleport-generator-core/src/uidl-schemas/component.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "component.json",
  "name": "Component UIDL",
  "type": "object",
  "required": ["name", "node"],
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string",
      "format": "uri"
    },
    "name": {
      "type": "string",
      "default": "MyComponent"
    },
    "node": {"$ref": "#/definitions/node"},
    "meta": {"type": "object"},
    "stateDefinitions":  { "$ref": "#/definitions/stateDefinitions" },
    "propDefinitions": { "$ref": "#/definitions/propDefinitions" }
  },
  "definitions": {
    "dependency": {
      "type": "object",
      "additionalProperties": false,
      "required": ["type"],
      "properties": {
        "type": {
          "type": "string",
          "enum": ["package", "local", "library"],
          "examples": ["package", "local", "library"]
        },
        "path": {"type": "string"},
        "version": {"type": "string", "default": "1.0.0"},
        "meta": {
          "type": "object", 
          "additionalProperties": false,
          "properties": {
            "namedImport": {"type": "boolean", "default": false},
            "originalName": {"type": "string"}
          }
        }
      }
    },
    "propDefinitions": {
      "type": "object",
      "patternProperties": {
        ".*": {
          "type": "object",
          "additionalProperties": false,
          "required": ["type"],
          "properties": {
            "type": {
              "type": "string",
              "enum": ["string", "boolean", "number", "array", "func", "object", "children"]
            },
            "defaultValue": {
              "oneOf": [
                { "type": "number" },
                { "type": "boolean" },
                { "type": "string" },
                { "type": "object" }, 
                {
                  "type": "array",
                  "items": {
                    "oneOf": [
                      { "type": "number" },
                      { "type": "string" },
                      { "type": "object" }
                    ]
                  }
                }
              ]
            },
            "isRequired": {
              "type": "boolean"
            },
            "meta": {"type": "object"}
          }
        }
      }
    },
    "stateDefinitions": {
      "type": "object",
      "patternProperties": {
        ".*": {
          "type": "object",
          "additionalProperties": false,
          "required": ["type", "defaultValue"],
          "properties": {
            "type": {"type":"string", "enum": ["string", "boolean", "number", "object", "func", "array", "router"]},
            "values": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "value": {},
                  "meta": { 
                    "type": "object",
                    "properties": {
                      "componentName": { "type": "string" },
                      "path": { "type": "string" },
                      "fileName": { "type": "string" }
                    }
                  },
                  "transitions": { "type": "object" }
                }
              }
            },
            "defaultValue": {},
            "actions": {"type": "array"}
          }
        }
      }
    },
    "node": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type":"object",
          "properties": {
            "type": {
              "type":"string",
              "enum": ["static", "dynamic", "element", "repeat","conditional","slot"]
            },
            "content": {
              "oneOf": [{
                "$ref": "#/definitions/staticValueContent" 
              },{
                "$ref": "#/definitions/dynamicReferenceContent"
              },{
                "$ref": "#/definitions/repeatNodeContent" 
              },{
                "$ref": "#/definitions/elementNodeContent"
              },{
                "$ref": "#/definitions/conditionalNodeContent"
              },{
                "$ref": "#/definitions/slotNodeContent"
              }]
            }
          }
        }
      ]
    },
    "staticValueContent": {
      "oneOf": [ 
        { "type": "string" },
        { "type": "number" },
        { "type": "boolean" },
        { "type": "array"} 
      ] 
    },
    "dynamicReferenceContent": {
      "type": "object",
      "required": ["referenceType","id" ],
      "additionalProperties": false,
      "properties": {
        "referenceType" :{
          "type": "string",
          "enum":  ["prop", "state", "local", "attr"]
        },
        "id": { "type": "string" }
      }
    },
    "repeatNodeContent": {
      "type": "object",
      "required": [ "node", "dataSource" ],
      "properties": {
        "node":{ "$ref": "#/definitions/node"},
        "dataSource":{"$ref": "#/definitions/attributeValue"},
        "meta": {
          "type":"object",
          "properties": {
            "useIndex": {"type": "boolean"},
            "iteratorName": {"type": "string"},
            "dataSourceIdentifier": {"type": "string"}
          }
        }
      }
    },
    "attributeValue": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": ["static", "dynamic"]
        },
        "content": {
          "oneOf": [
            {"$ref":"#/definitions/dynamicReferenceContent"},
            {"$ref":"#/definitions/staticValueContent"}
          ]
        }
      }
    },
    "conditionalNodeContent": {
      "type":"object",
      "required": [ "node", "reference" ],
      "properties": {
        "node":{ "$ref": "#/definitions/node"},
        "reference":{
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": ["dynamic"]
            },
            "content": {"$ref":"#/definitions/dynamicReferenceContent"}
          }
        },
        "value": {
          "oneOf": [ 
            { "type": "string" },
            { "type": "number" },
            { "type": "boolean" }
          ]
        },
        "condition": {"$ref":"#/definitions/conditionalExpression"}
      }
    },
    "conditionalExpression":{
      "type":"object",
      "required": ["conditions"],
      "properties": {
        "conditions":  {
          "type":"array",
          "items": {
            "type":"object",
            "required": ["operation"],
            "properties": {
              "operation": {"type": "string"}, 
              "operand": {
                "oneOf": [ 
                  { "type": "string" },
                  { "type": "number" },
                  { "type": "boolean" }
                ]
              }
            }
          }
        },
        "matchingCriteria": { "type": "string" }
      }
    },
    "elementNodeContent": {
      "type": "object",
      "required": ["elementType"],
      "additionalProperties": false,
      "properties": {
        "elementType": {"type": "string"},
        "name": {"type": "string"},
        "key": {"type": "string"},
        "dependency": {"$ref": "#/definitions/componentDependency"},
        "style": {"$ref": "#/definitions/styleDefinitions"},
        "attrs": {
          "type": "object",
           "patternProperties": {
            ".*": { "oneOf": [
              { "$ref": "#/definitions/attributeValue" },
              { "type": "string" },
              { "type": "number" },
              { "type": "boolean" },
              { "type": "array"}
            ] }
          }
        }, 
        "events":{"$ref": "#/definitions/eventDefinitions"},
        "children": { "type": "array", "items": {"$ref": "#/definitions/node"}}
      }
    },
    "componentDependency": {
      "type": "object",
      "required": ["type"],
      "properties": {
        "type": {"type": "string"},
        "path": {"type": "string"},
        "version": {"type": "string"},
        "meta": {
          "type":"object",
          "properties": {
            "namedImport": {"type": "boolean"},
             "originalName": {"type": "string"}
          }
        }
      }
    },
    "styleDefinitions":{
      "type": "object",
      "patternProperties": {
        ".*": { "oneOf": [
          { "$ref": "#/definitions/styleValue" },
          { "type": "string" },
          { "type": "number" },
          { 
            "type": "object",
            "patternProperties": {
              ".*": {"$ref": "#/definitions/styleDefinitions"}
            }
          }
        ] }
      }
    },
    "styleValue": {
      "type": "object",
      "oneOf": [
        {"$ref":"#/definitions/attributeValue"},
        {"$ref":"#/definitions/nestedStyleDeclaration"}
      ]
    },
    "nestedStyleDeclaration": {
      "type": "object",
      "required": ["type", "content"],
      "properties":{
        "type": {
          "type": "string",
          "enum": ["nested-style"]
        },
        "content":{"$ref": "#/definitions/styleDefinitions"}
      }
    },
    "eventDefinitions":{
      "type": "object",
      "patternProperties": {
        ".*": {
          "type":"array",
          "items": {
            "type": "object",
            "required": ["type"],
            "properties": {
              "type": {"type": "string"},
              "modifies": {"type": "string"},
              "newState": {
                "oneOf": [ 
                  { "type": "string" },
                  { "type": "number" },
                  { "type": "boolean" }
                ]
              },
              "calls": {"type": "string"},
              "args": { 
                "type": "array",
                "items": {
                  "oneOf": [ 
                    { "type": "string" },
                    { "type": "number" },
                    { "type": "boolean" }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "slotNodeContent": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "fallback": { "$ref": "#/definitions/node" },
        "name": { "type": "string" }
      }
    }  
  }      
}

=== teleporthq/teleport-code-generators/packages/teleport-component-generator-react/__tests__/integration/component-with-valid-state-reference.json
{
  "name": "StyledComponent",
  "stateDefinitions": {
    "active": {
      "type": "string",
      "defaultValue": "block"
    }
  },
  "propDefinitions": {
    "direction": {
      "type": "string",
      "defaultValue": "row"
    },
    "config": {
      "type": "object",
      "defaultValue": {
        "height": 32
      }
    }
  },
  "node": {
    "type": "element",
    "content": {
      "children": ["Hello There !",
        {
          "type": "element",
          "content": {
            "elementType": "button",
            "name": "click",
            "children": ["click me !"],
            "events": {
              "click": [
                {
                  "type": "stateChange",
                  "modifies": "active",
                  "newState": "none"
                }
              ]
            }
          }
        }
      ],
      "elementType": "container",
      "style": {
        "flexDirection": {
          "type": "dynamic",
          "content": {
            "referenceType": "prop",
            "id": "direction"
          }
        },
        "display": {
          "type": "dynamic",
          "content": {
            "referenceType": "state",
            "id": "active"
          }
        },
        "height": {
          "type": "dynamic",
          "content": {
            "referenceType": "prop",
            "id": "config.height"
          }
        },
        "alignSelf": {
          "type": "static",
          "content": "center"
        }
      }
    }
  }
}

=== teleporthq/teleport-code-generators/__tests__/fixtures/component-sample.json
{
  "name": "New UIDL",
  "propDefinitions": {
    "title": {
      "type": "string",
      "defaultValue": "Hello"
    },
    "items": {
      "type": "array",
      "defaultValue": []
    }
  },
  "stateDefinitions": {
    "isVisible": {
      "type": "boolean",
      "defaultValue": true
    }
  },
  "node": {
    "type": "element",
    "content": {
      "elementType": "container",
      "attrs": {
        "data-static-attr": {
          "type": "static",
          "content": "test"
        },
        "data-dynamic-attr": {
          "type": "dynamic",
          "content": {
            "referenceType": "prop",
            "id": "title"
          }
        }
      },
      "children": [
        {
          "type": "element",
          "content": {
            "elementType": "text",
            "children": [
              {
                "type": "static",
                "content": "Hello World!"
              },
              {
                "type": "dynamic",
                "content": {
                  "referenceType": "prop",
                  "id": "title"
                }
              }
            ]
          }
        },
        {
          "type": "repeat",
          "content": {
            "node": {
              "type": "element",
              "content": {
                "elementType": "text",
                "children": [
                  {
                    "type": "dynamic",
                    "content": {
                      "referenceType": "local",
                      "id": "item"
                    }
                  },
                  {
                    "type": "element",
                    "content": {
                      "elementType": "list",
                      "attrs": {
                        "items": {
                          "type": "static",
                          "content": ["angular", "react", "vue"]
                        }
                      }
                    }
                  }
                ]
              }
            },
            "dataSource": {
              "type": "dynamic",
              "content": {
                "referenceType": "prop",
                "id": "items"
              }
            },
            "meta": {
              "useIndex": true,
              "iteratorName": "item"
            }
          }
        },
        {
          "type": "conditional",
          "content": {
            "reference": {
              "type": "dynamic",
              "content": {
                "referenceType": "state",
                "id": "isVisible"
              }
            },
            "value": true,
            "node": {
              "type": "element",
              "content": {
                "elementType": "text",
                "children": [{
                  "type": "static",
                  "content": "Now you see me!"
                }]
              }
            }
          }
        }
      ]
    }
  }
}
